mvc_app/Models/Movie/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace mvc_app.Models.Movie
{
    public class Movie
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Director { get; set; }
        public string Genre { get; set; }
        //[DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{yyyy-MM-dd}")]
        public string ReleaseDate { get; set; }
        public string Description { get; set; }
        public string Poster { get; set; }
        public List<Movie> MovieList { get; set; } = new List<Movie>();

        public Movie(string title, string director, string genre, string releaseDate, string description, string poster)
        {
            Title = title;
            Director = director;
            Genre = genre;
            ReleaseDate = releaseDate;
            Description = description;
            Poster = poster;
        }

        public Movie()
        {
        }
    }
}

mvc_app/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mvc_app.Models.Movie;
using Newtonsoft.Json.Linq;

namespace mvc_app.Controllers
{
    public class MovieController : Controller
    {
        List<Movie> movies;

        public MovieController()
        {
            movies = new List<Movie>() {
                new Movie {Title="The Dark Knight",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="The Dark Knight",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="The Dark Knight",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="The Dark Knight",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="The Dark Knight",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="The Dark Knight",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="The Dark Knight",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="The Dark Knight",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="The Dark Knight",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="The Dark Knight",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="Tnight",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="The Dight",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="TheKnight",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="The Daght",Director=" Christopher Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="The Dt",Director=" Chrilan",Genre=" Action",ReleaseDate="18 Jy 2008",
                    Description ="When the menace sterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
                new Movie {Title="The Daright",Director=" Christopr Nolan",Genre=" Action",ReleaseDate="18 July 2008",
                    Description ="When thes from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                    Poster ="poster"},
            };
        }
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            IEnumerable<Movie> movies = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44347/api/");
                //HTTP GET
                var responseTask = client.GetAsync("movies");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<Movie>>();
                    readTask.Wait();

                    movies = readTask.Result;
                }
                else //web api sent error response 
                {
                    //log response status here..

                    movies = Enumerable.Empty<Movie>();

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            return View(movies);
        }

        //public ActionResult create()
        //{
        //    return View();
        //}
        [HttpPost]
        public async Task<ActionResult> insert(Movie movie)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44347/api/movies");

                //HTTP POST
                var postTask =await client.PostAsJsonAsync<Movie>("https://localhost:44347/api/movies", movie);
                //postTask.Wait();

                //var result = postTask.Result;
                if (postTask.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }

            ModelState.AddModelError(string.Empty, "Server Error. Please contact administrator.");

            return View(movie);
        }

        public ActionResult moveToCreate()
        {
            return View("insert");
        }
        public ActionResult Delete(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44347/api/");

                //HTTP DELETE
                var deleteTask = client.DeleteAsync("movies/" + id.ToString());
                deleteTask.Wait();

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index");
        }
    }
}

mvc_app/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mvc_app.Models;
using mvc_app.Models.Home;
using Newtonsoft.Json;

namespace mvc_app.Controllers
{
    public class TableController : Controller
    {
        private static int tempid;
        public async Task<IActionResult> DeleteRecord(string selectedid)
        {
            var client = new HttpClient();

            UserCollection Coltemp = new UserCollection();
            string baseUrl = "https://localhost:44347/api/GetAll";// for get
            string Url = "https://localhost:44347/api/RegisteredUsers/" + selectedid;//for delete
            
            try
            {
                var response = await client.DeleteAsync(Url);
                using (HttpResponseMessage res = await client.GetAsync(baseUrl))
                    {
                        using (HttpContent content = res.Content)
                        {
                            var data = await content.ReadAsStringAsync();
                            if (data != null)
                            {
                                List<RegisteredUser> test = JsonConvert.DeserializeObject<List<RegisteredUser>>(data);
                                foreach (var item in test)
                                {
                                    Coltemp.Usercol.Add(item);
                                }

                                Console.WriteLine("data------------{0}", data);
                            }
                            else
                            {
                                Console.WriteLine("NO Data----------");
                            }

                        }
                    }
            }
            catch (Exception exception)
            {
                Console.WriteLine("Exception Hit------------");
                Console.WriteLine(exception);
            }

            return View("Validate", Coltemp);
        }

       

        public async Task<IActionResult> Update(RegisteredUser user)
        {
            user.id = tempid;
            UserCollection Coltemp = new UserCollection();
            var client = new HttpClient();
            string Url = "https://localhost:44347/api/RegisteredUsers/"+user.id;
            string baseUrl = "https://localhost:44347/api/GetAll";
            var path = Path.Combine(
                Directory.GetCurrentDirectory(), "wwwroot/Files",
                user.SelectedFile.GetFilename());
            user.FileName = user.SelectedFile.GetFilename();
            using (var stream = new FileStream(path, FileMode.Create))
            {
                await user.SelectedFile.CopyToAsync(stream);
            }
            Coltemp.Usercol.Add(user);
            try
            {
                var response = client.PutAsJsonAsync<RegisteredUser>(Url, user);
                using (HttpResponseMessage res = await client.GetAsync(baseUrl))
                {
                    using (HttpContent content = res.Content)
                    {
                        var data = await content.ReadAsStringAsync();
                        if (data != null)
                        {
                            List<RegisteredUser> test = JsonConvert.DeserializeObject<List<RegisteredUser>>(data);
                            foreach (var item in test)
                            {
                                Coltemp.Usercol.Add(item);
                            }

                            
                        }
                        else
                        {
                            Console.WriteLine("NO Data----------");
                        }

                    }
                }
            }
            catch (Exception exception)
            {
                Console.WriteLine("Exception Hit------------");
                Console.WriteLine(exception);
            }

            return View("Validate", Coltemp);
        }


        public IActionResult MoveToEdit(int id)
        {
            RegisteredUser user=new RegisteredUser();
            tempid = id;
            return View("EditView",user);
        }
        public IActionResult RegisterUser()
        {
            return View("Index");
        }
        
    }
}

mvc_app/Views/Movie/TableView.cshtml
@model IEnumerable<mvc_app.Models.Movie.Movie>

@{
    ViewData["Title"] = "TableView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>TableView</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Director)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poster)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Director)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Poster)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

mvc_app/Views/Movie/create.cshtml
@model mvc_app.Models.Movie.Movie
@{
    ViewData["Title"] = "create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-lumen.css" />
<div style="display:flex;justify-content:center; flex-direction:column">
    <div style="display:flex;justify-content:center">
        <h2>create</h2>
    </div>
    <div class=" center-block">
        @using (Html.BeginForm("insert", "Movie"))
        {
            <div class="form-groupl">
                @Html.LabelFor(m => m.Title)
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
            </div>
            <div class="form-groupl">
                @Html.LabelFor(m => m.Director)
                @Html.TextBoxFor(m => m.Director, new { @class = "form-control" })
            </div>
            @Html.LabelFor(m => m.Genre)
            @*@Html.TextBoxFor(m => m.Genre, new { @class = "form-control" })*@
            <select asp-for="Genre" class="form-control">
                <option value="" hidden disabled selected>Select a Genre</option>
                <option value="comedy">Comedy</option>
                <option value="horror">Horror</option>
                <option value="romance">Romance</option>
                <option value="drama">Drama</option>
                <option value="thriller">Thriller</option>
                <option value="adventure">Adventure</option>
                <option value="action">Action</option>

            </select>
            <div class="form-groupl">
                @Html.LabelFor(m => m.ReleaseDate)
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>

            </div>
            <div class="form-groupl">
                @Html.LabelFor(m => m.Description)
                <textarea asp-for="Description" rows="4" cols="50" class=" form-control"></textarea>
            </div>
            <div class="form-groupl">
                @Html.LabelFor(m => m.Poster)
                <input type="file" asp-for="Poster" class="btn border-light m-3" multiple />
            </div>
            <div class="form-group" style="display:flex;justify-content:center;margin-top:20px ;flex-direction:column">
                <button type="submit" value="create" class="btn btn-dark border-info "> Create Record </button>

                <div style="display:flex;align-self:center;margin-top:15px">
                    @Html.ActionLink("Back", "Index")
                </div>

            </div>
        }
        
    </div>
</div>

mvc_app/Views/Movie/index.cshtml
@model IEnumerable<mvc_app.Models.Movie.Movie>
@{
    ViewData["Title"] = "index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="display:flex; justify-content:center">
    <h2>Movies Table</h2>
</div>
<div style="display:flex; justify-content:space-around">
    <table class="table table-bordered table-striped table-responsive table-hover ">
        <tr>
            <th>Movie ID </th>
            <th>Title</th>
            <th>Director</th>
            <th>Genre</th>
            <th>ReleaseDate</th>
            <th>Description</th>
            <th>Poster</th>
            <th>Actions</th>
        </tr>

        @foreach (var d in Model)
        {
            <tr>
                <td>@d.Id</td>
                <td>@d.Title</td>
                <td>@d.Director</td>
                <td>@d.Genre</td>
                <td>@d.ReleaseDate</td>
                <td>@d.Description</td>
                <td>@d.Poster</td>
                <td>
                    @*<div style="display:flex; justify-content:space-between; flex-direction:row">
            <a class="edit" style="margin-right:10px" title="Edit" data-toggle="tooltip">Update</a>

            <a class="delete" title="Delete" data-toggle="tooltip">Delete</a>
        </div>*@
                    @Html.ActionLink("Edit", "Edit", new { id = d.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = d.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = d.Id })
                </td>

            </tr>
        }


    </table>
</div>
<div style="margin:20px;display:flex;justify-content:center">
    <input name="create" value="Add Movie" id="addMovieBtn" title="Add Movie" class="btn btn-dark "
           onclick="window.location.href='@Url.Action( "moveToCreate","Movie")'" type="submit">
    
</div>

mvc_app/Views/Movie/insert.cshtml
@model mvc_app.Models.Movie.Movie

@{
    ViewData["Title"] = "insert";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>insert</h2>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="insert">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <input asp-for="Director" class="form-control" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poster" class="control-label"></label>
                <input asp-for="Poster" class="form-control" />
                <span asp-validation-for="Poster" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}