mvc_app/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using mvc_app.Models;
using Newtonsoft.Json;

namespace mvc_app.Controllers
{
    public class LoginController : Controller
    {
        private readonly HttpClient _httpClient = new HttpClient();
        private FileManager FManager;
        private IConfiguration configuration;
        private readonly string ApiUrl;
        private ApiHandler Handler;

        public LoginController(IConfiguration iConfig)
        {
            this.configuration = iConfig;
            this.FManager = new FileManager(configuration.GetSection("Manual_Settings").GetSection("FilePath").Value);
            this.ApiUrl = configuration.GetSection("Manual_Settings").GetSection("ApiUrl").Value;
            this.Handler = new ApiHandler(new Uri(ApiUrl));
        }

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public async Task<bool> Validate(Login login)
        {
            //Logins?userName=sahar&stringPassword=12345678

            var completeGetString = "Logins?userName="+ login.UserName+"&stringPassword="+login.plainPassword;
            var response = await _httpClient.GetAsync(ApiUrl + completeGetString);
            var data = await response.Content.ReadAsStringAsync();
            return JsonConvert.DeserializeObject<bool>(data);
        }

    }
}

mvc_app/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

using mvc_app.Models;

namespace mvc_app.Controllers
{
    public class RegisterController : Controller
    {
        //private  static List<StudentRegisterationModel> StudentList = new List<StudentRegisterationModel>();
        private PaginationModel Pages = new PaginationModel();
        private FileManager FManager;
        private IConfiguration configuration;
        private  readonly string ApiUrl;
        private ApiHandler Handler;
     
        public RegisterController(IConfiguration iConfig)
        {
            configuration = iConfig;
            FManager = new FileManager(configuration.GetSection("Manual_Settings").GetSection("FilePath").Value);
            ApiUrl = configuration.GetSection("Manual_Settings").GetSection("ApiUrl").Value;
            Handler = new ApiHandler(new Uri(ApiUrl)); //"https://localhost:44347/api/" 
            try
            {
                Pages.Count = Handler.GetTotalCount().Result;
            }catch(Exception e) { Content(e.ToString()); }

        }
    
        [HttpPost]
        public IActionResult InputView(StudentRegisterationModel M)
        {       
            if (M == null) { return View(); }
            return View(M);
        }     
        public IActionResult InputView(int id)
        {           
            return View(new StudentRegisterationModel(id));
        }
    
        public async Task<IActionResult> OutputView(int id=0, string type="",int pageNo=1,string sortBy="Id")
        {
            if (id != 0)
            {
                if (type == "Delete")
                  await  DeleteRecord(id);                        
            }           
            try
            {               
                Pages.StudentList = Handler.GetStudents(Pages.Currentpage=pageNo, sortBy, Pages.PageSize).Result;
            }
            catch (Exception e)
            {
                Content(e.ToString());
            }
            return View(Pages);       
        }
        [HttpPost]
  

        [HttpPost]
        public async Task<IActionResult> OutputView(StudentRegisterationModel M)
        {
            if (M.file == null) return Content("files not selected");
            await FManager.UploadFileAsync(M);               
            try
            {
                if (M.id != 0)
                    await EditRecord(M);
              
                else
                    await Handler.SaveUser(M);
            }
            catch (Exception e) { Content(e.ToString()); }
            try
            {
                Pages.Currentpage = 1;
                Pages.StudentList = Handler.GetStudents(1, "Id", Pages.PageSize).Result;
            }
            catch (Exception e) { Content(e.ToString()); }
            return View(Pages);
        }
       
        public IActionResult DownloadFile(string filename)
        {
            if (filename == null) return Content("filename is empty.");
           return FManager.DownloadFileAsync(filename).Result;
        }
        public async Task<IActionResult> DeleteRecord(int id)
        {
            StudentRegisterationModel M = new StudentRegisterationModel();
            M.id = id;
            try { await Handler.DeleteUser(M); }
            catch (Exception e) { Content(e.ToString()); }
            return RedirectToAction("OutputView");
        }
    
        public async Task<IActionResult> EditRecord(StudentRegisterationModel M)
        {
            try { await Handler.UpdateUser(M); }
            catch (Exception e) { Content(e.ToString()); }
            return RedirectToAction("OutputView");
        }       
     
    }
}                                                              

mvc_app/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mvc_app.Models;
using mvc_app.Models.Home;
using Newtonsoft.Json;

namespace mvc_app.Controllers
{
    public class TableController : Controller
    {
        private static int tempid;
        public async Task<IActionResult> DeleteRecord(string selectedid)
        {
            var client = new HttpClient();

            UserCollection Coltemp = new UserCollection();
            string baseUrl = "https://localhost:44347/api/GetAll";// for get
            string Url = "https://localhost:44347/api/RegisteredUsers/" + selectedid;//for delete
            
            try
            {
                var response = await client.DeleteAsync(Url);
                using (HttpResponseMessage res = await client.GetAsync(baseUrl))
                    {
                        using (HttpContent content = res.Content)
                        {
                            var data = await content.ReadAsStringAsync();
                            if (data != null)
                            {
                                List<RegisteredUser> test = JsonConvert.DeserializeObject<List<RegisteredUser>>(data);
                                foreach (var item in test)
                                {
                                    Coltemp.Usercol.Add(item);
                                }

                                Console.WriteLine("data------------{0}", data);
                            }
                            else
                            {
                                Console.WriteLine("NO Data----------");
                            }

                        }
                    }
            }
            catch (Exception exception)
            {
                Console.WriteLine("Exception Hit------------");
                Console.WriteLine(exception);
            }

            return View("Validate", Coltemp);
        }

       

        public async Task<IActionResult> Update(RegisteredUser user)
        {
            user.id = tempid;
            UserCollection Coltemp = new UserCollection();
            var client = new HttpClient();
            string Url = "https://localhost:44347/api/RegisteredUsers/"+user.id;
            string baseUrl = "https://localhost:44347/api/GetAll";
            var path = Path.Combine(
                Directory.GetCurrentDirectory(), "wwwroot/Files",
                user.SelectedFile.GetFilename());
            user.FileName = user.SelectedFile.GetFilename();
            using (var stream = new FileStream(path, FileMode.Create))
            {
                await user.SelectedFile.CopyToAsync(stream);
            }
            Coltemp.Usercol.Add(user);
            try
            {
                var response = client.PutAsJsonAsync<RegisteredUser>(Url, user);
                using (HttpResponseMessage res = await client.GetAsync(baseUrl))
                {
                    using (HttpContent content = res.Content)
                    {
                        var data = await content.ReadAsStringAsync();
                        if (data != null)
                        {
                            List<RegisteredUser> test = JsonConvert.DeserializeObject<List<RegisteredUser>>(data);
                            foreach (var item in test)
                            {
                                Coltemp.Usercol.Add(item);
                            }

                            
                        }
                        else
                        {
                            Console.WriteLine("NO Data----------");
                        }

                    }
                }
            }
            catch (Exception exception)
            {
                Console.WriteLine("Exception Hit------------");
                Console.WriteLine(exception);
            }

            return View("Validate", Coltemp);
        }


        public IActionResult MoveToEdit(int id)
        {
            RegisteredUser user=new RegisteredUser();
            tempid = id;
            return View("EditView",user);
        }
        public IActionResult RegisterUser()
        {
            return View("Index");
        }
        
    }
}

mvc_app/Views/Shared/EditView.cshtml
@model mvc_app.Models.RegisteredUser
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<link rel="StyleSheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
<div class="container" align="center">
    <div class="card bg-light">
        <article class="card-body mx-auto" style="max-width: 400px;">
            <h4 class="card-title mt-3 text-center">Edit Account</h4>
            <p class="text-center">Get started with editing this account </p>
            <form asp-action="Update" asp-controller="Table" method="post" enctype="multipart/form-data">
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                    </div>

                    <input asp-for="Name" class="form-control" placeholder="Full Name" type="text">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                    </div>
                    <input asp-for="email_address" class="form-control" placeholder="Email address" type="email">
                    <span asp-validation-for="email_address" class="text-danger"></span>
                </div>
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-phone"></i> </span>
                    </div>
                    <select class="custom-select" style="max-width: 120px;">
                        <option selected="">+92</option>
                        <option value="1">+92</option>
                    </select>
                    <input asp-for="phone_number" class="form-control" placeholder="Phone Number" type="text">
                    <span asp-validation-for="phone_number" class="text-danger"></span>
                </div>
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-building"></i> </span>
                    </div>
                    <select asp-for="job_type" class="form-control">
                        <option selected=""> Select job type</option>
                        <option>Designer</option>
                        <option>Manager</option>
                        <option>Accounting</option>
                    </select>
                </div>
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input asp-for="password" class="form-control" placeholder="Create password" type="password">
                    <span asp-validation-for="password" class="text-danger"></span>
                </div>
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input asp-for="password" class="form-control" placeholder="Repeat password" type="password">
                    <span asp-validation-for="password" class="text-danger"></span>
                </div>
                <div>
                    <input asp-for="SelectedFile" type="file" class="btn btn-success btn-block" multiple />
                    <button type="submit" class="btn btn-primary btn-block"> Update  </button>
                </div>
            </form>
            <br>
            <br>
            <br>
            <form asp-action="MoveToTable" asp-controller="Home" method="post" enctype="multipart/form-data">
                <button type="submit" class="btn btn-primary btn-block"> Back To Table View  </button>
            </form>

        </article>
    </div>
</div>

<br><br>

mvc_app/Views/Shared/Index.cshtml
@model mvc_app.Models.Login


<div class="container" align="center">
    <div class="card bg-light">
        <article class="card-body mx-auto" style="max-width: 400px;">
            <h4 class="card-title mt-3 text-center">Sign In</h4>
            <p class="text-center">Provide credentials to Sign In</p>
            <form asp-action="Validate" asp-controller="Login" method="post" enctype="multipart/form-data">
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                    </div>

                    <input asp-for="UserName" class="form-control" placeholder="Full name" type="text">
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                    </div>
                    <input asp-for="plainPassword" class="form-control" placeholder="password" type="password">
                    <span asp-validation-for="plainPassword" class="text-danger"></span>
                </div>
                
                <br>
                <br>
                
                    <button type="submit" class="btn btn-primary btn-block"> Login  </button>
                
            </form>
        </article>
    </div>
</div>

<br><br>

mvc_app/Views/Shared/Validate.cshtml
@{
    ViewData["Title"] = "Validate";
}

@model mvc_app.Models.UserCollection

<head><link rel="stylesheet" type="text/css" href="css/TableStyle.css" /></head>
<body>
<form asp-action="RegisterUser" asp-controller="Table">
    <button type="submit" class="btn btn-success"> Register User </button>
</form>
<table class="container" id="myTable">
    <thead>
    <tr>
        <th >#</th>
        <th ><a asp-action="MoveToTable" asp-controller="Home" asp-route-sortby="name"> Name</a></th>
        <th ><a asp-action="MoveToTable" asp-controller="Home" asp-route-sortby="email_address">Email Address</a></th>
        <th ><a asp-action="MoveToTable" asp-controller="Home" asp-route-sortby="phone_number">Phone Number</a></th>
        <th ><a asp-action="MoveToTable" asp-controller="Home" asp-route-sortby="job_type">Job Type</a></th>
        <th ><a asp-action="MoveToTable" asp-controller="Home" asp-route-sortby="file_name">File Name</a></th>
    </tr>
    </thead>
    <tbody id="myTableBody">
    @{
        int i = 0;
        @foreach (var item in Model.Usercol)
         {
             i++;
             <tr>
                 <td>@i</td>
                 <td>@item.Name</td>
                 <td>@item.email_address</td>
                 <td>@item.phone_number</td>
                 <td>@item.job_type</td>
                 <td><a asp-action="Download" asp-route-filename="@item.FileName">@item.FileName</a></td>
                 <td><a asp-action="DeleteRecord" asp-controller="Table" asp-route-selectedid="@item.id">delete</a></td>
                 <td><a asp-action="MoveToEdit" asp-controller="Table" asp-route-id="@item.id">edit</a></td>
             </tr>

         }
    }

    </tbody>
</table>
<ul>
    @for (int x = 1; x <= ViewBag.count; x++)
        {
            <li><a asp-action="MoveToTable" asp-controller="Home" asp-route-pagenum="@x">@x</a></li>
        }
</ul>

</body>

mvc_app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <style>
        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
        }

        li {
            float: left;
        }

        li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li a:hover {
            background-color: #111;
        }
    </style>
</head>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - mvc_app</title>

    <environment include="Development">
        @*<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" id="bootstrap-css">
        <link rel="StyleSheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">*@

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
        @*<link rel="stylesheet" type="text/css" href="~/css/TableStyle.css"/>*@

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>
</head>
<body>

<ul class="navbar-fixed-top">
    <li><a asp-area="" asp-controller="user" asp-action="userpage">Userpage</a></li>
    <li><a asp-area="" asp-controller="Home" asp-action="Index">Register User</a></li>
    <li><a asp-area="" asp-controller="Register" asp-action="OutputView">Student Registerations</a></li>
</ul>
<partial name="_CookieConsentPartial"/>

<div>
    @RenderBody()
</div>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", required: false)
</body>
</html>